apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: golang-app
    version: ${VERSION}
  name: golang-app
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
      - image: 10.168.0.76:9000/dev-registry/golang-app:${VERSION}
        name: golang
      imagePullSecrets:
      - name : nexus-secret