apiVersion: v1
kind: Service
metadata:
  name: golang-app-service
  namespace: kavish-test
spec:
  selector:
    app: golang-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
